SET NAMES utf8mb4;
UPDATE employer_profiles SET industry = 'Công nghệ thông tin' WHERE id = 3;
UPDATE employer_profiles SET industry = 'Đa ngành' WHERE id = 4;
UPDATE employer_profiles SET industry = 'Công nghệ thông tin' WHERE id = 5;
UPDATE employer_profiles SET industry = 'Thương mại điện tử' WHERE id = 6;
UPDATE employer_profiles SET industry = 'Thương mại điện tử' WHERE id = 8;
UPDATE employer_profiles SET industry = 'Du lịch & Khách sạn' WHERE id = 10;
UPDATE employer_profiles SET industry = 'Giáo dục' WHERE id = 11;
UPDATE employer_profiles SET company_description = 'FPT Software là công ty phần mềm hàng đầu Việt Nam với hơn 30.000 nhân viên toàn cầu. Chuyên cung cấp giải pháp chuyển đổi số, AI và dịch vụ CNTT cho các tập đoàn đa quốc gia.' WHERE id = 3;
UPDATE employer_profiles SET company_description = 'Vingroup là tập đoàn kinh tế tư nhân lớn nhất Việt Nam hoạt động đa ngành: bất động sản, công nghệ, y tế, giáo dục, thương mại điện tử và sản xuất ô tô điện VinFast.' WHERE id = 4;
UPDATE employer_profiles SET company_description = 'VNG là công ty công nghệ hàng đầu Việt Nam, nổi tiếng với Zalo, ZaloPay và các sản phẩm game. VNG được định giá trên 1 tỷ USD (kỳ lân công nghệ).' WHERE id = 5;
UPDATE employer_profiles SET company_description = 'Tiki là nền tảng thương mại điện tử hàng đầu Việt Nam với hơn 50 triệu lượt truy cập mỗi tháng. Nổi tiếng với dịch vụ TikiNOW giao hàng trong 2 giờ.' WHERE id = 6;
UPDATE employer_profiles SET company_description = 'MoMo là ví điện tử số 1 Việt Nam với hơn 31 triệu người dùng. Cung cấp dịch vụ thanh toán, chuyển tiền, mua sắm trực tuyến và các dịch vụ tài chính.' WHERE id = 7;
UPDATE employer_profiles SET company_description = 'Shopee là nền tảng thương mại điện tử hàng đầu Đông Nam Á, thuộc tập đoàn Sea Group (Singapore). Tại Việt Nam, Shopee có hơn 5.000 nhân viên.' WHERE id = 8;
UPDATE employer_profiles SET company_description = 'VNPAY là công ty công nghệ tài chính hàng đầu Việt Nam, cung cấp giải pháp thanh toán điện tử QR code cho hơn 40 ngân hàng và tổ chức tài chính.' WHERE id = 9;
UPDATE employer_profiles SET company_description = 'Saigontourist là tổng công ty du lịch hàng đầu Việt Nam với hệ thống khách sạn 5 sao, công ty lữ hành và trung tâm hội nghị quốc tế.' WHERE id = 10;
UPDATE employer_profiles SET company_description = 'Vinschool là hệ thống giáo dục từ mầm non đến THPT thuộc Vingroup, áp dụng chương trình quốc tế Cambridge và IB với hơn 40 cơ sở trên toàn quốc.' WHERE id = 11;
UPDATE employer_profiles SET address = 'Tòa nhà FPT, Phố Duy Tân, Cầu Giấy, Hà Nội' WHERE id = 3;
UPDATE employer_profiles SET address = '7 Bằng Lăng 1, Vinhomes Riverside, Long Biên, Hà Nội' WHERE id = 4;
UPDATE employer_profiles SET address = '182 Lê Đại Hành, P.15, Q.11, TP. Hồ Chí Minh' WHERE id = 5;
UPDATE employer_profiles SET address = '52 Út Tịch, P.4, Q. Tân Bình, TP. Hồ Chí Minh' WHERE id = 6;
UPDATE employer_profiles SET address = 'Tầng 7, Tòa nhà Centec, 72-74 Nguyễn Thị Minh Khai, Q.3, TP. Hồ Chí Minh' WHERE id = 7;
UPDATE employer_profiles SET address = 'Tòa nhà Etown Central, 11 Đoàn Văn Bơ, Q.4, TP. Hồ Chí Minh' WHERE id = 8;
UPDATE employer_profiles SET address = 'Tầng 8, 22 Láng Hạ, Ba Đình, Hà Nội' WHERE id = 9;
UPDATE employer_profiles SET address = '23 Lê Lợi, Q.1, TP. Hồ Chí Minh' WHERE id = 10;
UPDATE employer_profiles SET address = 'Ocean Park, Gia Lâm, Hà Nội' WHERE id = 11;